=== Neo4jClient

Spring Data Neo4j⚡️RX comes with a Neo4j Client, providing a human readable layer on top of Neo4js Java driver.
It has the following main goals

0. Integrate into Springs transaction management, for both imperative and reactive scenarios
0. Participate in JTA-Transactions if necessary
0. Provide a consistent API for both imperative and reactive scenarios
0. Don't add any mapping overhead

SDN-RX relies on all those features and uses them to fulfill it's entity mapping features.

The https://github.com/neo4j/neo4j-java-driver[plain java driver] is a very versatile tool
and provides an asynchronous API in addition to the imperative and reactive versions.
SDN-RX uses it as directly as possible while being as user friendly and idiomatic as possible, too.

The Neo4j Client comes in two flavors:

* `org.springframework.data.neo4j.core.Neo4jClient`
* `org.springframework.data.neo4j.core.ReactiveNeo4jClient`

While both versions provide an API using the same vocabulary and syntax, they are not API compatible.

==== Imperative or reactive?

Interactions with one Neo4j client usually ends with a call to

* `fetch().one()`
* `fetch().first()`
* `fetch().all()`
* `run()`

The imperative version will interact at this moment with the database
and get the requested results or summary, wrapped in a `Optional<>` or a `Collection`.

The reactive version will in contrast return a publisher of the requested type.
Interaction with the database and retrieval of the results will not happen until the publisher is subscribed to.
The publisher can only be subscribed once.

==== Getting an instance of the client

As with most things in SDN-RX, both clients depend on a configured driver instance.

[[create-imperative-client]]
[source,java]
.Creating an instance of the imperative Neo4j client
----
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;

import org.org.springframework.data.neo4j.core.Neo4jClient;

public class Demo

    public static void main(String...args) {

        Driver driver = GraphDatabase
            .driver("neo4j://localhost:7687", AuthTokens.basic("neo4j", "password");

        Neo4jClient client = Neo4jClient.create(driver);
    }
}
----

The driver can only open a reactive session against a 4.0 database and will fail with an exception on any lower version.

[[create-reactive-client]]
[source,java]
.Creating an instance of the reactive Neo4j client
----
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;

import org.org.springframework.data.neo4j.core.ReactiveNeo4jClient;

public class Demo

    public static void main(String...args) {

        Driver driver = GraphDatabase
            .driver("neo4j://localhost:7687", AuthTokens.basic("neo4j", "password");

        ReactiveNeo4jClient client = ReactiveNeo4jClient.create(driver);
    }
}
----

NOTE: Make sure you use the same driver instance for the client as you used for providing a `Neo4jTransactionManager` or `ReactiveNeo4jTransactionManager`
in case you have enabled transactions.
The client won't be able to synchronize transactions if you use another instance of a driver.

Our Spring Boot starter provides ready to use beans of the Neo4j client that fit the environment (imperative or reactive)
and you usually don't have to configure your own instance.


==== Interacting directly with the driver while using managed transactions

In case you don't want or don't like the oppionated "client" approach of the `Neo4jClient` or the `ReactiveNeo4jClient`,
you can have the client delegate all interactions with the database to your code.