:springVersion: 5.2.0.RELEASE
:spring-framework-docs: https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference
:spring-framework-javadoc: https://docs.spring.io/spring/docs/{springVersion}/javadoc-api

[[preface]]
= Preface

The Spring Data Neo4j project applies Spring Data concepts to the development of solutions using the Neo4j graph data store.
We provide _"repositories"_ as a high-level abstraction for storing and querying documents as well as templates and clients for generic domain access or generic query execution.
All of them are integrated with Spring's application transactions.

[[preface.nosql]]
== NoSQL and Graph databases

A graph database is a storage engine that is specialised in storing and retrieving vast networks of information.
It efficiently stores data as nodes with relationships to other or even the same nodes,
thus allowing high-performance retrieval and querying of those structures.
Properties can be added to both nodes and relationships.
Nodes can be labelled by zero or more labels, relationships are always directed and named.

Graph databases are well suited for storing most kinds of domain models.
In almost all domains, there are certain things connected to other things.
In most other modelling approaches, the relationships between things are reduced to a single link without identity and attributes.
Graph databases allow to keep the rich relationships that originate from the domain equally well-represented in the database without resorting to also modelling the relationships as "things".
There is very little "impedance mismatch" when putting real-life domains into a graph database.


[[preface.nosql.neo4j]]
=== Introducing Neo4j

https://neo4j.com/[Neo4j] is an open source NoSQL graph database.
It is a fully transactional database (ACID) that stores data structured as graphs consisting of nodes, connected by relationships.
Inspired by the structure of the real world, it allows for high query performance on complex data, while remaining intuitive and simple for the developer.

The starting point for learning about Neo4j is https://neo4j.com/[neo4j.com].
Here is a list of useful resources:

* The https://neo4j.com/docs/[Neo4j documentation] introduces Neo4j and contains links to getting started guides, reference documentation and tutorials.
* The https://neo4j.com/sandbox/[online sandbox] provides a convenient way to interact with a Neo4j instance in combination with the online https://neo4j.com/developer/get-started/[tutorial].
* Neo4j https://neo4j.com/developer/java/[Java Bolt Driver]
* Neo4j https://neo4j.com/docs/ogm-manual/current/[Neo4j Object Graph Mapper (OGM) Library]
* Several https://neo4j.com/books/[books] available for purchase and https://www.youtube.com/neo4j[videos] to watch.


[[preface.spring-data]]
== Spring and Spring Data

Spring Data uses Spring framework's https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[core] functionality,
such as the https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#beans[IoC] container,
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#core-convert[type conversion system],
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[expression language],
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/integration.html#jmx[JMX integration],
and portable https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html#dao-exceptions[DAO exception hierarchy].
While it is not important to know the Spring APIs, understanding the concepts behind them is.
At a minimum, the idea behind IoC should be familiar for whatever IoC container you choose to use.

The core functionality of the Neo4j support can be used directly, through either the `Neo4jClient` or the `Neo4jTemplate` or the reactive variants thereof.
All of them provide integration with Spring's application level transactions.
On a lower level, you can grab the Bolt driver instance, but than you have to manage your own transactions

To learn more about Spring, you can refer to the comprehensive documentation that explains in detail the Spring Framework.
There are a lot of articles, blog entries and books on the matter - take a look at the Spring framework https://spring.io/docs[home page ] for more information.

== What is Spring Data Neo4j⚡️RX

Spring Data Neo4j⚡️RX is the successor to Spring Data Neo4j + Neo4j-OGM.
The separate layer of Neo4j-OGM (Neo4j Object Graph Mapper) has been replaced by Spring infrastructure, but the basic concepts of an Object Graph Mapper (OGM) still apply:

An OGM maps nodes and relationships in the graph to objects and references in a domain model.
Object instances are mapped to nodes while object references are mapped using relationships, or serialized to properties (e.g. references to a Date).
JVM primitives are mapped to node or relationship properties.
An OGM abstracts the database and provides a convenient way to persist your domain model in the graph and query it without using low level drivers.
It also provides the flexibility to the developer to supply custom queries where the queries generated by SDN/RX are insufficient.
